### ISSUE TITLE
Dorado basecalling crashes with CUDA error on RTX 5070 Ti (flatten_parameters / torch.zeros)

### ISSUE THREAD

**Issue by brandonlukas** [epi2me-labs/wf-basecalling#69]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 24.04 via WSL2 (Windows 11)

### Workflow Version

v1.4.7-g3f2a21d

### Workflow Execution

Command line (Local)

### CLI command run

```
nextflow run epi2me-labs/wf-basecalling \
	--basecaller_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.1.0' \
	--dorado_ext 'pod5' \
	--input 'input' \
	--ref 'GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta' \
	--remora_cfg 'dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2' \
	-profile standard
```

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hi team,

I'm running `wf-basecalling` with `ontresearch/dorado:sha4644018526d3644d92a9e680ab8f2d1eeff2e272` (and also tested `ontresearch/dorado:latest`) on WSL2 (Ubuntu 24.04 distro) with an **NVIDIA RTX 5070 Ti**, NVIDIA-SMI version 570.124.06, driver version 572.70, and CUDA version 12.8.

```
Fri Apr  4 09:52:24 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 572.70         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5070 Ti     On  |   00000000:01:00.0  On |                  N/A |
|  0%   33C    P8             21W /  300W |    1362MiB /  16303MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              25      G   /Xwayland                             N/A      |
|    0   N/A  N/A              31      G   /Xwayland                             N/A      |
+-----------------------------------------------------------------------------------------+
```

**Even when using the demo dataset,** Dorado crashes at the basecalling step with this traceback:
```
torch::nn::detail::RNNImplBase<torch::nn::LSTMImpl>::flatten_parameters()
...
c10::cuda::c10_cuda_check_implementation
...
torch.zeros(..., dtype=torch.float16)
```

Is this GPU officially supported yet, or could this be a compatibility issue with newer Ada GPUs?

### Relevant log output

```shell
N E X T F L O W   ~  version 24.10.5

Launching `https://github.com/epi2me-labs/wf-basecalling` [deadly_goldstine] DSL2 - revision: 3f2a21dc5d [master]

WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-basecalling v1.4.7-g3f2a21d
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : deadly_goldstine
  containerEngine: docker
  container      : [withLabel:wf_basecalling:ontresearch/dorado:sha4644018526d3644d92a9e680ab8f2d1eeff2e272, withLabel:wf_common:ontresearch/wf-common:sha9ef2f4e4585c4ce6a604616e77185077551abf50]
  launchDir      : /mnt/wdssd/pingyin/longreads/wf-basecalling-demo
  workDir        : /mnt/wdssd/pingyin/longreads/wf-basecalling-demo/work
  projectDir     : /home/brandon/.nextflow/assets/epi2me-labs/wf-basecalling
  userName       : brandon
  profile        : standard
  configFiles    : /home/brandon/.nextflow/assets/epi2me-labs/wf-basecalling/nextflow.config, /mnt/wdssd/pingyin/longreads/wf-basecalling-demo/nextflow.config

Input Options
  input          : input
  ref            : GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta

Basecalling options
  basecaller_cfg : dna_r10.4.1_e8.2_400bps_hac@v4.1.0
  remora_cfg     : dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-basecalling for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-basecalling v1.4.7-g3f2a21d.
--------------------------------------------------------------------------------
executor >  local (7)
[cc/f7f119] prepare_reference:faidx (1)      | 0 of 1
[25/e8f869] prepare_reference:cram_cache (1) | 0 of 1
[8b/96fc42] prepare_reference:make_mmi (1)   | 0 of 1
[e5/00c939] wf_dorado:dorado (3)             | 0 of 3
[-        ] wf_dorado:align_and_qsFilter     -
[-        ] wf_dorado:merge_pass_calls       -
[-        ] wf_dorado:merge_fail_calls       -
[2b/3a8aeb] getVersions                      | 1 of 1 ✔
[8f/70f8da] getParams                        | 1 of 1 ✔
[-        ] bamstats                         -
[-        ] progressive_stats                -
[-        ] makeReport                       -
[-        ] output_last                      -
[-        ] output_stream                    -
ERROR ~ Error executing process > 'wf_dorado:dorado (1)'

Caused by:
  Process `wf_dorado:dorado (1)` terminated with an error exit status (1)


Command executed:

  # CW-2569: convert the pod5s contextually
  if [[ "false" == "true" && "pod5" == "fast5" ]]; then
      pod5 convert fast5 ./*.fast5 --output . --threads 8 --one-to-one ./
  fi

  # Run dorado on the new pod5s
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.1.0         .         --modified-bases-models ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2                                             --device cuda:all | samtools view --no-PG -b -o 0.ubam -

  # CW-2569: delete the pod5s, if emit not required.
  if [[ "false" == "true" && "pod5" == "fast5" ]]; then
      rm -r converted/
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  frame #18: at::native::cudnn_rnn::copy_weights_to_flat_buf_views(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool, cudnnDataType_t, c10::TensorOptions const&, bool, bool, bool) + 0x3d0 (0x7f1efed047d0 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #19: at::native::_cudnn_rnn_flatten_weight(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool) + 0x90 (0x7f1efed05410 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #20: <unknown function> + 0xa630fe9 (0x7f1f0094afe9 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #21: <unknown function> + 0xa66700f (0x7f1f0098100f in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #22: <unknown function> + 0x52c4fc4 (0x7f1efb5defc4 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #23: at::_ops::_cudnn_rnn_flatten_weight::call(c10::ArrayRef<at::Tensor>, long, c10::SymInt, long, c10::SymInt, c10::SymInt, long, bool, bool) + 0x386 (0x7f1efb551536 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #24: <unknown function> + 0x80b3c06 (0x7f1efe3cdc06 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #25: torch::nn::detail::RNNImplBase<torch::nn::LSTMImpl>::flatten_parameters() + 0x346 (0x7f1efe3d6d26 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #26: void torch::nn::Module::m c10_cuda_check_implementation at /pytorch/pyold/c10/cuda/CUDAException.cpp:44 (most recent call first):
  frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f1f00d529b7 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f1efa2d7115 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f1f00d1c958 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #3: void at::native::gpu_kernel_impl<at::native::FillFunctor<c10::Half> >(at::TensorIteratorBase&, at::native::FillFunctor<c10::Half> const&) + 0x9b1 (0x7f1eff53de11 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #4: void at::native::gpu_kernel<at::native::FillFunctor<c10::Half> >(at::TensorIteratorBase&, at::native::FillFunctor<c10::Half> const&) + 0x33b (0x7f1eff53e63b in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #5: <unknown function> + 0x9216dd5 (0x7f1eff530dd5 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #6: at::native::fill_kernel_cuda(at::TensorIterator&, c10::Scalar const&) + 0x20 (0x7f1eff531f00 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #7: <unknown function> + 0x49823a3 (0x7f1efac9c3a3 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #8: <unknown function> + 0xa61c4b3 (0x7f1f009364b3 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #9: at::_ops::fill__Scalar::call(at::Tensor&, c10::Scalar const&) + 0x12c (0x7f1efb3ed92c in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #10: at::native::zero_(at::Tensor&) + 0xa7 (0x7f1efac9ca67 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #11: <unknown function> + 0xa61b80d (0x7f1f0093580d in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #12: at::_ops::zero_::call(at::Tensor&) + 0x129 (0x7f1efb82a499 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #13: at::native::zeros_symint(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0x160 (0x7f1efaf469c0 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #14: <unknown function> + 0x588d645 (0x7f1efbba7645 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #15: at::_ops::zeros::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0xd5 (0x7f1efb3a6715 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #16: <unknown function> + 0x56c4835 (0x7f1efb9de835 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #17: at::_ops::zeros::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0x1b1 (0x7f1efb4012a1 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #18: at::native::cudnn_rnn::copy_weights_to_flat_buf_views(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool, cudnnDataType_t, c10::TensorOptions const&, bool, bool, bool) + 0x3d0 (0x7f1efed047d0 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #19: at::native::_cudnn_rnn_flatten_weight(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool) + 0x90 (0x7f1efed05410 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #20: <unknown function> + 0xa630fe9 (0x7f1f0094afe9 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #21: <unknown function> + 0xa66700f (0x7f1f0098100f in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #22: <unknown function> + 0x52c4fc4 (0x7f1efb5defc4 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #23: at::_ops::_cudnn_rnn_flatten_weight::call(c10::ArrayRef<at::Tensor>, long, c10::SymInt, long, c10::SymInt, c10::SymInt, long, bool, bool) + 0x386 (0x7f1efb551536 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #24: <unknown function> + 0x80b3c06 (0x7f1efe3cdc06 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #25: torch::nn::detail::RNNImplBase<torch::nn::LSTMImpl>::flatten_parameters() + 0x346 (0x7f1efe3d6d26 in /home/
executor >  local (7)
[cc/f7f119] prepare_reference:faidx (1)      | 0 of 1
[25/e8f869] prepare_reference:cram_cache (1) | 0 of 1
[8b/96fc42] prepare_reference:make_mmi (1)   | 0 of 1
[11/8ba2e1] wf_dorado:dorado (1)             | 1 of 3, failed: 1
[-        ] wf_dorado:align_and_qsFilter     -
[-        ] wf_dorado:merge_pass_calls       -
[-        ] wf_dorado:merge_fail_calls       -
[2b/3a8aeb] getVersions                      | 1 of 1 ✔
[8f/70f8da] getParams                        | 1 of 1 ✔
[-        ] bamstats                         -
[-        ] progressive_stats                -
[-        ] makeReport                       -
[-        ] output_last                      -
[-        ] output_stream                    -
ERROR ~ Error executing process > 'wf_dorado:dorado (1)'

Caused by:
  Process `wf_dorado:dorado (1)` terminated with an error exit status (1)


Command executed:

  # CW-2569: convert the pod5s contextually
  if [[ "false" == "true" && "pod5" == "fast5" ]]; then
      pod5 convert fast5 ./*.fast5 --output . --threads 8 --one-to-one ./
  fi

  # Run dorado on the new pod5s
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.1.0         .         --modified-bases-models ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.1.0_5mCG_5hmCG@v2                                             --device cuda:all | samtools view --no-PG -b -o 0.ubam -

  # CW-2569: delete the pod5s, if emit not required.
  if [[ "false" == "true" && "pod5" == "fast5" ]]; then
      rm -r converted/
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  frame #18: at::native::cudnn_rnn::copy_weights_to_flat_buf_views(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool, cudnnDataType_t, c10::TensorOptions const&, bool, bool, bool) + 0x3d0 (0x7f1efed047d0 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #19: at::native::_cudnn_rnn_flatten_weight(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool) + 0x90 (0x7f1efed05410 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #20: <unknown function> + 0xa630fe9 (0x7f1f0094afe9 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #21: <unknown function> + 0xa66700f (0x7f1f0098100f in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #22: <unknown function> + 0x52c4fc4 (0x7f1efb5defc4 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #23: at::_ops::_cudnn_rnn_flatten_weight::call(c10::ArrayRef<at::Tensor>, long, c10::SymInt, long, c10::SymInt, c10::SymInt, long, bool, bool) + 0x386 (0x7f1efb551536 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #24: <unknown function> + 0x80b3c06 (0x7f1efe3cdc06 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #25: torch::nn::detail::RNNImplBase<torch::nn::LSTMImpl>::flatten_parameters() + 0x346 (0x7f1efe3d6d26 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #26: void torch::nn::Module::m c10_cuda_check_implementation at /pytorch/pyold/c10/cuda/CUDAException.cpp:44 (most recent call first):
  frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f1f00d529b7 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f1efa2d7115 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f1f00d1c958 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #3: void at::native::gpu_kernel_impl<at::native::FillFunctor<c10::Half> >(at::TensorIteratorBase&, at::native::FillFunctor<c10::Half> const&) + 0x9b1 (0x7f1eff53de11 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #4: void at::native::gpu_kernel<at::native::FillFunctor<c10::Half> >(at::TensorIteratorBase&, at::native::FillFunctor<c10::Half> const&) + 0x33b (0x7f1eff53e63b in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #5: <unknown function> + 0x9216dd5 (0x7f1eff530dd5 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #6: at::native::fill_kernel_cuda(at::TensorIterator&, c10::Scalar const&) + 0x20 (0x7f1eff531f00 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #7: <unknown function> + 0x49823a3 (0x7f1efac9c3a3 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #8: <unknown function> + 0xa61c4b3 (0x7f1f009364b3 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #9: at::_ops::fill__Scalar::call(at::Tensor&, c10::Scalar const&) + 0x12c (0x7f1efb3ed92c in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #10: at::native::zero_(at::Tensor&) + 0xa7 (0x7f1efac9ca67 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #11: <unknown function> + 0xa61b80d (0x7f1f0093580d in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #12: at::_ops::zero_::call(at::Tensor&) + 0x129 (0x7f1efb82a499 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #13: at::native::zeros_symint(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0x160 (0x7f1efaf469c0 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #14: <unknown function> + 0x588d645 (0x7f1efbba7645 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #15: at::_ops::zeros::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0xd5 (0x7f1efb3a6715 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #16: <unknown function> + 0x56c4835 (0x7f1efb9de835 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #17: at::_ops::zeros::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0x1b1 (0x7f1efb4012a1 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #18: at::native::cudnn_rnn::copy_weights_to_flat_buf_views(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool, cudnnDataType_t, c10::TensorOptions const&, bool, bool, bool) + 0x3d0 (0x7f1efed047d0 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #19: at::native::_cudnn_rnn_flatten_weight(c10::ArrayRef<at::Tensor>, long, long, long, long, long, long, bool, bool) + 0x90 (0x7f1efed05410 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #20: <unknown function> + 0xa630fe9 (0x7f1f0094afe9 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #21: <unknown function> + 0xa66700f (0x7f1f0098100f in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #22: <unknown function> + 0x52c4fc4 (0x7f1efb5defc4 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #23: at::_ops::_cudnn_rnn_flatten_weight::call(c10::ArrayRef<at::Tensor>, long, c10::SymInt, long, c10::SymInt, c10::SymInt, long, bool, bool) + 0x386 (0x7f1efb551536 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #24: <unknown function> + 0x80b3c06 (0x7f1efe3cdc06 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #25: torch::nn::detail::RNNImplBase<torch::nn::LSTMImpl>::flatten_parameters() + 0x346 (0x7f1efe3d6d26 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #26: void torch::nn::Module::to_impl<c10::Device&, bool&>(c10::Device&, bool&) + 0xd0 (0x7f1efe300030 in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #27: torch::nn::Module::to(c10::Device, bool) + 0x1c (0x7f1efe2f921c in /home/epi2melabs/dorado/lib/libdorado_torch_lib.so)
  frame #28: dorado() [0xb6880d]
  frame #29: dorado() [0xb68cf4]
  frame #30: dorado() [0xb57c58]
  frame #31: dorado() [0xb5838d]
  frame #32: dorado() [0xa358e9]
  frame #33: dorado() [0x8cb9db]
  frame #34: dorado() [0x88cbbb]
  frame #35: dorado() [0x891a6b]
  frame #36: dorado() [0x4f6a00]
  frame #37: __libc_start_main + 0xf3 (0x7f1ef5212083 in /usr/lib/x86_64-linux-gnu/libc.so.6)
  frame #38: dorado() [0x823f5f]

  [main_samview] fail to read the header from "-".

Work dir:
  /mnt/wdssd/pingyin/longreads/wf-basecalling-demo/work/11/8ba2e191214260694589a538933798

Container:
  ontresearch/dorado:sha4644018526d3644d92a9e680ab8f2d1eeff2e272

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (4)
```

### Application activity log entry

```shell

```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

### Other demo data information

```shell

```

**Comment by brandonlukas** [comment]
The issue is related to ( [Dorado issue #1247](https://github.com/nanoporetech/dorado/issues/1247)). Basically, Dorado v0.9.5 is needed for newer NVIDIA GPUs (e.g., RTX 5070 Ti), but the `ontresearch/dorado` image is still pinned to v0.9.1.

If anyone needs an immediate fix, here's how I solved the issue (with help from ChatGPT):

**1. Extract model files from the original image**
Pull the official image and copy the /models directory locally:

```
docker create --name temp-dorado ontresearch/dorado:latest bash
docker cp temp-dorado:/models ./models
docker rm temp-dorado
```

**2. Create custom Dockerfile**
Here's the `Dockerfile` I used:

```
# Use CUDA 12.8.1 with cuDNN, Ubuntu 22.04
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

LABEL maintainer="Brandon & ChatGPT"
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install OS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    git \
    unzip \
    samtools \
    python3 \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Symlink python -> python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# Upgrade pip and install PyTorch nightly with CUDA 12.8
RUN pip3 install --upgrade pip
RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

# Install Dorado v0.9.5 (latest as of April 2025)
RUN wget https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.9.5-linux-x64.tar.gz && \
    tar -xzf dorado-0.9.5-linux-x64.tar.gz && \
    mv dorado-0.9.5-linux-x64 dorado && \
    ln -s /app/dorado/bin/dorado /usr/local/bin/dorado && \
    rm dorado-0.9.5-linux-x64.tar.gz

# Create model and manifests paths used by wf-basecalling
ENV DRD_MODELS_PATH=/models
ENV DRD_MANIFESTS_PATH=/data/dorado_models
RUN mkdir -p /models /data/dorado_models

# Set library path (important for dorado!)
ENV LD_LIBRARY_PATH=/app/dorado/lib:$LD_LIBRARY_PATH

# Add models to the image
COPY models /models

ENV DRD_MODELS_PATH=/models

# Default shell
CMD ["bash"]

```

**3. Build the image**

```
docker build -t brandon/dorado:0.9.5-gpu .
```

Verify that Dorado v0.9.5 is installed and the /models directory is there:
```
docker run --rm brandon/dorado:0.9.5-gpu dorado --version
docker run --rm brandon/dorado:0.9.5-gpu ls /models
```

**4. Update nextflow.config to use the new image**
Add this to your `nextflow.config` file:

```
process {
  withLabel: 'wf_dorado' {
    container = 'brandon/dorado:0.9.5-gpu'
  }
}
```

**Comment by brandonlukas** [comment]
The issue is related to [Dorado issue #1247](https://github.com/nanoporetech/dorado/issues/1247).

Basically, Dorado v0.9.5 is needed for newer NVIDIA GPUs (e.g., RTX 5070 Ti), but `ontresearch/dorado` images are still pinned to v0.9.1.

If anyone needs an immediate fix, pull down this docker image:
```
docker pull blukas4/dorado:0.9.5-cuda12.8
```

Then modify your `nextflow.config` to include:
```
process {
  withLabel: 'wf_dorado' {
    container = 'blukas4/dorado:0.9.5-cuda12.8'
  }
}
```

**Comment by brandonlukas** [comment]
A new tag was released 12 hours ago and works:

```
process {
  withLabel: 'wf_dorado' {
    container = 'ontresearch/dorado:mr597_shaa11826e5ca013816017f05d50c65e560a34f77fd'
  }
}
```
